### ISSUE TITLE
Error related to keras

### ISSUE THREAD

**Issue by SExpert12** [Luca96/carla-driving-rl-agent#30]
Hi, I am getting this error. I tried to change as suggested in this but still I am not able to run the file.

pygame 2.0.1 (SDL 2.0.14, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
/home/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
WARNING:tensorflow:From main.py:9: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2024-06-26 03:13:12.082157: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2024-06-26 03:13:12.104117: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3593325000 Hz
2024-06-26 03:13:12.105007: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fe1cc000b60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2024-06-26 03:13:12.105049: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2024-06-26 03:13:12.107924: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2024-06-26 03:13:12.134793: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2024-06-26 03:13:12.134833: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: 
2024-06-26 03:13:12.134841: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: zenten
2024-06-26 03:13:12.134935: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 535.171.4
2024-06-26 03:13:12.134959: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 535.171.4
2024-06-26 03:13:12.134966: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 535.171.4
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from core import learning
  File "/home/carla-driving-rl-agent-master/core/__init__.py", line 2, in <module>
    from core.carla_agent import CARLAgent, FakeCARLAEnvironment
  File "/home/carla-driving-rl-agent-master/core/carla_agent.py", line 8, in <module>
    import rl
  File "/home/carla-driving-rl-agent-master/rl/__init__.py", line 1, in <module>
    import rl.augmentations
  File "/home/carla-driving-rl-agent-master/rl/augmentations/__init__.py", line 2, in <module>
    from rl.augmentations.augmentations import *
  File "/home/carla-driving-rl-agent-master/rl/augmentations/augmentations.py", line 7, in <module>
    from rl import utils
  File "/home/carla-driving-rl-agent-master/rl/utils.py", line 16, in <module>
    from tensorflow.keras.optimizers.schedules import LearningRateSchedule
  File "/home/.local/lib/python3.8/site-packages/tensorflow/keras/__init__.py", line 19, in <module>
    from . import datasets
  File "/home/.local/lib/python3.8/site-packages/tensorflow/keras/datasets/__init__.py", line 14, in <module>
    from . import imdb
  File "/home/.local/lib/python3.8/site-packages/tensorflow/keras/datasets/imdb/__init__.py", line 11, in <module>
    from tensorflow.python.keras.datasets.imdb import get_word_index
  File "/home/.local/lib/python3.8/site-packages/tensorflow/python/keras/datasets/imdb.py", line 25, in <module>
    from tensorflow.python.keras.preprocessing.sequence import _remove_long_seq
  File "/home/.local/lib/python3.8/site-packages/tensorflow/python/keras/preprocessing/__init__.py", line 26, in <module>
    from tensorflow.python.keras.preprocessing import image
  File "/home/.local/lib/python3.8/site-packages/tensorflow/python/keras/preprocessing/image.py", line 23, in <module>
    from keras_preprocessing import image
  File "/home/.local/lib/python3.8/site-packages/keras_preprocessing/image.py", line 20, in <module>
    backend = get_keras_submodule('backend')
  File "/home/.local/lib/python3.8/site-packages/keras_preprocessing/__init__.py", line 24, in get_keras_submodule
    raise ImportError('You need to first `import keras` '
ImportError: You need to first `import keras` in order to use `keras_preprocessing`. For instance, you can do:

```
import keras
from keras_preprocessing import image
```

Or, preferably, this equivalent formulation:

```
from keras import preprocessing

**Comment by Luca96** [comment]
There are multiple errros. First, there is a mismatch in pandas version, then it seems that CUDA in not properly installed, and lastly, keras failing for some reason...

Could you list the packages along their version you have installed (I presume) in a virtualenv?

**Comment by SExpert12** [comment]
Hi, 
Thanks for your reply. This is the list of packages:
Package                 Version
----------------------- -----------
absl-py                 2.1.0
astunparse              1.6.3
cachetools              5.3.3
carla                   0.9.15
certifi                 2024.6.2
charset-normalizer      3.3.2
cloudpickle             3.0.0
cycler                  0.12.1
decorator               5.1.1
dm-tree                 0.1.8
fonttools               4.53.0
gast                    0.3.3
google-auth             2.30.0
google-auth-oauthlib    1.0.0
google-pasta            0.2.0
grpcio                  1.64.1
gym                     0.26.2
gym-notices             0.0.8
h5py                    2.10.0
idna                    3.7
importlib_metadata      8.0.0
Keras-Preprocessing     1.1.2
kiwisolver              1.4.5
Markdown                3.6
MarkupSafe              2.1.5
matplotlib              3.5.3
networkx                3.1
numpy                   1.18.5
oauthlib                3.2.2
opencv-python           4.10.0.84
opt-einsum              3.3.0
packaging               24.1
pillow                  10.3.0
pip                     24.1
protobuf                3.20.0
pyasn1                  0.6.0
pyasn1_modules          0.4.0
pygame                  2.6.0
pyparsing               3.1.2
python-dateutil         2.9.0.post0
requests                2.32.3
requests-oauthlib       2.0.0
rsa                     4.9
scipy                   1.9.3
setuptools              70.1.0
six                     1.16.0
tensorboard             2.14.0
tensorboard-data-server 0.7.2
tensorflow              2.3.1
tensorflow-estimator    2.3.0
tensorflow-probability  0.11.1
termcolor               2.4.0
urllib3                 2.2.2
Werkzeug                3.0.3
wheel                   0.43.0
wrapt                   1.16.0
zipp                    3.19.2


Now I am getting this error.
Hello from the pygame community. https://www.pygame.org/contribute.html
2024-06-27 02:24:12.741430: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2024-06-27 02:24:12.741458: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From main.py:36: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2024-06-27 02:24:13.392218: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-27 02:24:13.421715: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3593325000 Hz
2024-06-27 02:24:13.422517: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x321a060 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2024-06-27 02:24:13.422540: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2024-06-27 02:24:13.425373: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2024-06-27 02:24:13.453204: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2024-06-27 02:24:13.453237: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: ryzen
2024-06-27 02:24:13.453243: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: ryzen
2024-06-27 02:24:13.453309: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 535.171.4
2024-06-27 02:24:13.453326: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 535.171.4
2024-06-27 02:24:13.453330: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 535.171.4
/home/rlagent/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.15 
WARNING: Simulator API version  = 0.9.14-6-g43b5e7064-dirty 
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.15 
WARNING: Simulator API version  = 0.9.14-6-g43b5e7064-dirty 
Weather changed to WeatherParameters(cloudiness=5.000000, precipitation=0.000000, precipitation_deposits=0.000000, wind_intensity=10.000000, sun_azimuth_angle=-1.000000, sun_altitude_angle=45.000000, fog_density=2.000000, fog_distance=0.750000, fog_falloff=0.100000, wetness=0.000000, scattering_intensity=1.000000, mie_scattering_scale=0.030000, rayleigh_scattering_scale=0.033100, dust_storm=0.000000).
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    stage1.run2(epochs=100, epoch_offset=0)
  File "/home/rlagent/core/learning.py", line 146, in run2
    self.init()
  File "/home/rlagent/core/learning.py", line 117, in init
    self.agent = self.agent_class(self.env, **self.agent_args)
  File "/home/rlagent/core/carla_agent.py", line 97, in __init__
    super().__init__(*args, name=name, network=network_spec, clip_norm=clip_norm, **kwargs)
  File "/home/rlagent/rl/agents/ppo.py", line 36, in __init__
    super().__init__(*args, name=name, **kwargs)
  File "/home/rlagent/rl/agents/agents.py", line 28, in __init__
    self.set_random_seed(seed)
  File "/home/rlagent/rl/agents/agents.py", line 70, in set_random_seed
    self.env.seed(seed)
AttributeError: 'CARLAEnv' object has no attribute 'seed'

Thanks once again for your reply.

**Comment by Luca96** [comment]
@SExpert12 I think you need to downgrade `gym`  to version 0.20.1 or 0.19.6. I don't remember the exact version so the last number may be wrong, so please double-check. Also let me know which version of gym works for you so that I'll update the requirements file

**Comment by SExpert12** [comment]
Sure. Thanks for quick reply. Let me check and get back to you.

Thanks once again for your help.

**Comment by SExpert12** [comment]
Hi,
I got error related to numpy and tensorflow. So I installed the latest tensorflow. I am sharing package details.

Package                      Version
---------------------------- -------------------
absl-py                      2.1.0
astunparse                   1.6.3
cachetools                   5.3.3
carla                        0.9.15
certifi                      2024.6.2
charset-normalizer           3.3.2
cloudpickle                  1.6.0
contourpy                    1.1.1
cycler                       0.12.1
decorator                    5.1.1
dm-tree                      0.1.8
flatbuffers                  24.3.25
fonttools                    4.53.0
gast                         0.3.3
google-auth                  2.30.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.64.1
gym                          0.19.0
h5py                         2.10.0
idna                         3.7
importlib-metadata           8.0.0
importlib-resources          6.4.0
keras                        2.8.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.5
libclang                     18.1.1
Markdown                     3.6
MarkupSafe                   2.1.5
matplotlib                   3.7.5
networkx                     3.1
numpy                        1.20.0
oauthlib                     3.2.2
opencv-python                4.10.0.84
opt-einsum                   3.3.0
packaging                    24.1
pillow                       10.3.0
pip                          21.0
protobuf                     3.20.0
pyasn1                       0.6.0
pyasn1-modules               0.4.0
pygame                       2.6.0
pyparsing                    3.1.2
python-dateutil              2.9.0.post0
requests                     2.32.3
requests-oauthlib            2.0.0
rsa                          4.9
scipy                        1.10.1
setuptools                   65.5.0
six                          1.16.0
tensorboard                  2.8.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.8.0
tensorflow-estimator         2.3.0
tensorflow-io-gcs-filesystem 0.34.0
tensorflow-probability       0.11.1
termcolor                    2.4.0
tf-estimator-nightly         2.8.0.dev2021122109
typing-extensions            4.12.2
urllib3                      2.2.2
werkzeug                     3.0.3
wheel                        0.38.0
wrapt                        1.16.0
zipp                         3.19.2

The program is started to run but I am getting error related to spawn point. It is chosen randomly and I don't understand how to change. 

pygame 2.6.0 (SDL 2.28.4, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
2024-06-27 07:37:20.235303: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-06-27 07:37:20.235335: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From main.py:36: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2024-06-27 07:37:21.297341: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-27 07:37:21.325344: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2024-06-27 07:37:21.325401: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: ryzen
2024-06-27 07:37:21.325410: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: ryzen
2024-06-27 07:37:21.325602: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 535.171.4
2024-06-27 07:37:21.325639: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 535.171.4
2024-06-27 07:37:21.325647: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 535.171.4
/home/ryzen/rlagent/rlagent/lib/python3.8/site-packages/gym/logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.15 
WARNING: Simulator API version  = 0.9.14-6-g43b5e7064-dirty 
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.15 
WARNING: Simulator API version  = 0.9.14-6-g43b5e7064-dirty 
Weather changed to WeatherParameters(cloudiness=5.000000, precipitation=0.000000, precipitation_deposits=0.000000, wind_intensity=10.000000, sun_azimuth_angle=-1.000000, sun_altitude_angle=45.000000, fog_density=2.000000, fog_distance=0.750000, fog_falloff=0.100000, wetness=0.000000, scattering_intensity=1.000000, mie_scattering_scale=0.030000, rayleigh_scattering_scale=0.033100, dust_storm=0.000000).
Random seed 51 set.
Random seed 695516342 set.
state_spec: {'state_image': (90, 360, 3), 'state_navigation': (5,), 'state_road': (9,), 'state_vehicle': (4,)}
action_shape: 2
distribution: beta
2024-06-27 07:37:25.600724: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Optimizer: adam.
Optimizer: adam.
Optimizer: adam.
Random seed 2362446593 set.
env.reset
No recommended values for 'speed' attribute
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    stage1.run2(epochs=100, epoch_offset=0)
  File "/home/rlagent/core/learning.py", line 154, in run2
    self.reinforcement_learning()
  File "/home/rlagent/core/learning.py", line 184, in reinforcement_learning
    self.agent.learn(**self.learn_args['agent'])
  File "/home/rlagent/rl/agents/ppo.py", line 492, in learn
    state = self.env.reset()
  File "/home/rlagent/core/carla_env.py", line 212, in reset
    return super().reset()
  File "/home/rlagent/rl/environments/carla/environment.py", line 940, in reset
    observation = super().reset()
  File "/home/rlagent/rl/environments/carla/environment.py", line 228, in reset
    self.reset_world()
  File "/home/rlagent/core/carla_env.py", line 221, in reset_world
    super().reset_world()
  File "/home/rlagent/rl/environments/carla/environment.py", line 517, in reset_world
    self.vehicle: carla.Vehicle = env_utils.spawn_actor(self.world, blueprint, self.origin)
  File "/home/rlagent/rl/environments/carla/env_utils.py", line 218, in spawn_actor
    raise ValueError(f'Cannot spawn actor. Try changing the spawn_point ({spawn_point.location}) to something else.')
ValueError: Cannot spawn actor. Try changing the spawn_point (Location(x=-9.441488, y=91.994293, z=0.275307)) to something else.


Please help me resolve this issue also.
Thanks

**Comment by SExpert12** [comment]
Hi, 
I tried multiple towns.
I run the CARLA server first and then I run the main.py. I got this error.

pygame 2.6.0 (SDL 2.28.4, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
2024-06-27 07:49:39.607306: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-06-27 07:49:39.607340: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From main.py:36: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2024-06-27 07:49:40.837347: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-27 07:49:40.867943: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2024-06-27 07:49:40.867984: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: ryzen
2024-06-27 07:49:40.867993: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: ryzen
2024-06-27 07:49:40.868090: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 535.171.4
2024-06-27 07:49:40.868116: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 535.171.4
2024-06-27 07:49:40.868122: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 535.171.4
/home/ryzen/rlagent/rlagent/lib/python3.8/site-packages/gym/logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.15 
WARNING: Simulator API version  = 0.9.14-6-g43b5e7064-dirty 
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.15 
WARNING: Simulator API version  = 0.9.14-6-g43b5e7064-dirty 
Weather changed to WeatherParameters(cloudiness=5.000000, precipitation=0.000000, precipitation_deposits=0.000000, wind_intensity=10.000000, sun_azimuth_angle=-1.000000, sun_altitude_angle=45.000000, fog_density=2.000000, fog_distance=0.750000, fog_falloff=0.100000, wetness=0.000000, scattering_intensity=1.000000, mie_scattering_scale=0.030000, rayleigh_scattering_scale=0.033100, dust_storm=0.000000).
Random seed 51 set.
Random seed 695516342 set.
state_spec: {'state_image': (90, 360, 3), 'state_navigation': (5,), 'state_road': (9,), 'state_vehicle': (4,)}
action_shape: 2
distribution: beta
2024-06-27 07:49:46.662932: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Optimizer: adam.
Optimizer: adam.
Optimizer: adam.
Random seed 2362446593 set.
env.reset
No recommended values for 'speed' attribute
Event CARLAEvent.RESET triggered.
Sensor sensor.other.collision is already been started!
Sensor sensor.other.imu is already been started!
Sensor sensor.camera.rgb is already been started!
Sensor sensor.camera.rgb is already been started!
Sensor sensor.camera.rgb is already been started!
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    stage1.run2(epochs=100, epoch_offset=0)
  File "/home/rlagent/core/learning.py", line 154, in run2
    self.reinforcement_learning()
  File "/home/rlagent/core/learning.py", line 184, in reinforcement_learning
    self.agent.learn(**self.learn_args['agent'])
  File "/home/rlagent/rl/agents/ppo.py", line 492, in learn
    state = self.env.reset()
  File "/home/rlagent/core/carla_env.py", line 212, in reset
    return super().reset()
  File "/home/rlagent/rl/environments/carla/environment.py", line 940, in reset
    observation = super().reset()
  File "/home/rlagent/rl/environments/carla/environment.py", line 235, in reset
    self.skip(num_frames=self.num_frames_to_skip)
  File "/home/rlagent/rl/environments/carla/environment.py", line 412, in skip
    self.synchronous_context.tick(timeout=self.timeout)
  File "/home/rlagent/rl/environments/carla/tools/synchronous_mode.py", line 60, in tick
    data[name] = self._get_sensor_data(q, timeout)
  File "/home/rlagent/rl/environments/carla/tools/synchronous_mode.py", line 83, in _get_sensor_data
    data = sensor_queue.get(timeout=timeout)
  File "/usr/lib/python3.8/queue.py", line 178, in get
    raise Empty
_queue.Empty

and then I run client again without refreshing server then I got the spawning error.

**Comment by Luca96** [comment]
@SExpert12 Hello, and sorry for the late response. So, sometimes the CARLA simulator behaves a bit buggy so you need to close it and restart, again. This is because it can happen that the previously spawned vehicle is somehow not being destroyed: if so the episode will end prematurely, say on timestep 1.

**Comment by SExpert12** [comment]
Hi,  
I am again getting this same error. I created new venv and started from the beginning. 

Hello from the pygame community. https://www.pygame.org/contribute.html
2024-07-04 11:11:52.131612: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-07-04 11:11:52.131641: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From main.py:36: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2024-07-04 11:11:53.140409: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-04 11:11:53.173150: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2024-07-04 11:11:53.173197: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: ryzen
2024-07-04 11:11:53.173209: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: ryzen
2024-07-04 11:11:53.173315: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 535.183.1
2024-07-04 11:11:53.173349: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 535.183.1
2024-07-04 11:11:53.173360: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 535.183.1
/home/ryzen/rlagent/lucaagent/lib/python3.8/site-packages/gym/logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.14 
WARNING: Simulator API version  = 0.9.14-6-g43b5e7064-dirty 
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.14 
WARNING: Simulator API version  = 0.9.14-6-g43b5e7064-dirty 
Weather changed to WeatherParameters(cloudiness=5.000000, cloudiness=5.000000, precipitation=0.000000, precipitation_deposits=0.000000, wind_intensity=10.000000, sun_azimuth_angle=-1.000000, sun_altitude_angle=45.000000, fog_density=2.000000, fog_distance=0.750000, fog_falloff=0.100000, wetness=0.000000, scattering_intensity=1.000000, mie_scattering_scale=0.030000, rayleigh_scattering_scale=0.033100, dust_storm=0.000000).
sees 2338741697
Random seed 2338741697 set.
state_spec: {'state_image': (90, 360, 3), 'state_navigation': (5,), 'state_road': (9,), 'state_vehicle': (4,)}
action_shape: 2
distribution: beta
2024-07-04 11:11:57.492185: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Optimizer: adam.
Optimizer: adam.
Optimizer: adam.
sees 3235473884
Random seed 3235473884 set.
env.reset
No recommended values for 'speed' attribute
Event CARLAEvent.RESET triggered.
Sensor sensor.other.collision is already been started!
Sensor sensor.other.imu is already been started!
Sensor sensor.camera.rgb is already been started!
Sensor sensor.camera.rgb is already been started!
Sensor sensor.camera.rgb is already been started!
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    stage1.run2(epochs=100, epoch_offset=0)
  File "/home/rlagent/core/learning.py", line 154, in run2
    self.reinforcement_learning()
  File "/home/rlagent/core/learning.py", line 184, in reinforcement_learning
    self.agent.learn(**self.learn_args['agent'])
  File "/home/rlagent/rl/agents/ppo.py", line 492, in learn
    state = self.env.reset()
  File "/home/rlagent/core/carla_env.py", line 212, in reset
    return super().reset()
  File "/home/rlagent/rl/environments/carla/environment.py", line 940, in reset
    observation = super().reset()
  File "/home/rlagent/rl/environments/carla/environment.py", line 235, in reset
    self.skip(num_frames=self.num_frames_to_skip)
  File "/home/rlagent/rl/environments/carla/environment.py", line 412, in skip
    self.synchronous_context.tick(timeout=self.timeout)
  File "/home/rlagent/rl/environments/carla/tools/synchronous_mode.py", line 60, in tick
    data[name] = self._get_sensor_data(q, timeout)
  File "/home/rlagent/rl/environments/carla/tools/synchronous_mode.py", line 83, in _get_sensor_data
    data = sensor_queue.get(timeout=timeout)
  File "/usr/lib/python3.8/queue.py", line 178, in get
    raise Empty
_queue.Empty

How to solve this?

**Comment by allenwang-git** [comment]
wondering how you resolve above queue.Empty errors eventually? I have exact the same errors
